accounts/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('sign_up/',views.SignUp.as_view(), name='sign_up'),
    path('login/', views.SignIn.as_view(), name='sign_in'),
    path('logout/', views.Exit.as_view(), name='log_out')
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('showcase.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showcase/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Index.as_view(), name='index'),
    path('brands/<slug:slug>/', views.BrandDetail.as_view(), name='brand_detail'),
    path('phones/<slug:slug>/', views.PhoneDetail.as_view(), name='phone_detail'),
    path('create_phone/', views.PhoneCreate.as_view(), name='create_phone'),
    path('create_brand/', views.BrandCreate.as_view(), name='create_brand'),
    path('search/', views.Search.as_view(), name='search'),
    path('phones', views.PhonesList.as_view(), name='phones')
    
]

accounts/models.py
from django.db import models

# Create your models here.

showcase/models.py
from django.db import models
from pytils.translit import slugify
from django.urls import reverse_lazy

# class Product(models.Model):
#     type = models.

class Brand(models.Model):
    brand_name = models.CharField(max_length=200,verbose_name='Бренд')
    models_list = models.ManyToManyField('Phone_model',verbose_name='Список моделей', blank=True)
    brand_logo = models.ImageField(upload_to='brand_logos', verbose_name='Логотип')
    slug = models.SlugField(blank=True,unique=True)

    def __str__(self):
        return self.brand_name

    def save(self):
        self.slug = slugify(self.brand_name)
        super(Brand,self).save()

    def  get_absolute_url(self):
        return reverse_lazy('brand_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

class Phone_model(models.Model):
    phone_brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING, verbose_name='Производитель')
    phone_model = models.CharField(max_length=200, verbose_name='Модель')
    phone_image = models.ImageField(upload_to='phones',verbose_name='Фото телефона')
    phone_specs = models.TextField(verbose_name='Спецификации')
    slug = models.SlugField(unique=True,blank=True)

    def __str__(self):
        return str(self.phone_brand)+" "+ str(self.phone_model)

    def save(self):
        self.slug = slugify(str(self.phone_brand)+str(self.phone_model))
        super(Phone_model,self).save()
        brand = Brand.objects.filter(brand_name=str(self.phone_brand)).first()
        brand.models_list.add(self)
        brand.save()

    def  get_absolute_url(self):
        return reverse_lazy('phone_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Телефон'
        verbose_name_plural = 'Телефоны'

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=False)
    class Meta:
        model = User
        fields = ('username', 'password1','password2','email')

# class SignIn()

showcase/forms.py
from django import forms
from . import models

class BrandForm(forms.ModelForm):
    class Meta:
        model = models.Brand
        exclude = ('slug','models_list')

class PhoneForm(forms.ModelForm):
    class Meta:
        model = models.Phone_model
        exclude = ('slug',)
        

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView, LogoutView
from .forms import SignUpForm
from django.urls import reverse_lazy

class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'accounts/sign_up.html'
    success_url = reverse_lazy('sign_in')

class SignIn(LoginView):
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('index')
class Exit(LogoutView):
    next_page = reverse_lazy('index')

showcase/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView,CreateView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models,forms
from django.urls import reverse_lazy,reverse
from django.core.paginator import Paginator

class Index(ListView):
    model = models.Brand
    template_name='showcase/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        phone_list = models.Phone_model.objects.all()[:3]
        context['phone_list'] = phone_list
        return context

class PhonesList(ListView):
    paginate_by = 5
    model = models.Phone_model
    template_name = 'showcase/phone_list.html'
    context_object_name = 'phones_list'


class BrandDetail(DetailView):
    model = models.Brand
    template_name = 'showcase/brand_detail.html'

class PhoneDetail(DetailView):
    model = models.Phone_model
    template_name = 'showcase/phone_detail.html'
    context_object_name = 'phone'


class PhoneCreate(LoginRequiredMixin,CreateView):
    form_class = forms.PhoneForm
    template_name = 'showcase/phone_create.html'
    success_url = reverse_lazy('index')
    def get_success_url(self):
        return reverse('phone_detail', kwargs={'slug':self.object.slug})

class BrandCreate(LoginRequiredMixin,CreateView):
    form_class = forms.BrandForm
    template_name = 'showcase/brand_create.html'
    def get_success_url(self):
        return reverse('brand_detail', kwargs={'slug':self.object.slug})

class Search(View):
    def get_objects(self,name_startwith=''):
        objects_list = []
        if name_startwith:
            objects_brand = models.Phone_model.objects.filter(phone_brand=1)
            objects_list = models.Phone_model.objects.filter(phone_model__istartswith=name_startwith)
            # print(name_startwith)
            print(objects_list)
            print(objects_brand[0])
            # objects_list.extend(objects_brand)
        return objects_list

    def get(self,request):
        search_list = []
        starts_with = request.GET['search_bar']
        search_list = self.get_objects(starts_with)
        # print(search_list)
        return render(request, 'showcase/search.html',{'search_list':search_list})

templates/accounts/login.html
{% extends 'showcase/base.html' %}

{% block title %}
    Вход
{% endblock title %}
    

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Вход</button>
    </form>
{% endblock content %}
    

templates/accounts/sign_up.html
{% extends 'showcase/base.html' %}

{% block title %}
    Регистрация
{% endblock title %}
    

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Подтвердить</button>
    </form>
{% endblock content %}
    

templates/showcase/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <script src="{% static "js/jquery.js" %}"></script>
    <link  href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <script src="{% static "scripts/ajax.js" %}"></script>
    <title>
        
        {% block title %}
            
        {% endblock title %}
            
    </title>
    <body>
        <a href="{% url 'index' %}"> Домой</a>
        {% if user.is_authenticated %}
            Привет, {{ user.username }}!
            <a href="{% url 'create_phone' %}">Добавить телефон</a>
            <a href="{% url 'create_brand' %}">Добавить производителя</a> 
            <a href="{% url 'log_out' %}">Выход</a>
        {% else %}
            <a href="{% url 'sign_up' %}">Регистрация</a>
            <a href="{% url 'sign_in' %}">Войти</a>
        {% endif %}<br>
        <input class="form-control me-2" type="search" placeholder="Поиск по статьям" 
        aria-label="Search" id="search_bar">
        <div class="container"  id="search_list">
        </div>
        {% block content %}
            
        {% endblock content %}
            
    </body>
</html>

templates/showcase/brand_create.html
{% extends 'showcase/base.html' %}

{% block title %}
    Create brand
{% endblock title %}
    

{% block content %}
    <form method="POST" enctype="multipart/form-data" action="{% url 'create_brand' %}">
        {% csrf_token %}
        
        {% for f in form %}
            {{ f }}<br>
        {% endfor %}
        <button type="submit">Добавить</button>
    </form>

{% endblock content %}
    

templates/showcase/brand_detail.html
{% extends 'showcase/base.html' %}

{% block title %}
    {{ brand.brand_name }}
{% endblock title %}


{% block content %}
    <h1>{{ brand.brand_name }}</h1><br>
    <img src="{{ brand.brand_logo.url }}"><br>
    
    {% if brand.models_list.all %}
        <h3>Телефоны</h3>
        <ul>
            {% for model in brand.models_list.all %}
                <li><a href="{{ model.get_absolute_url }}">{{ model }}<br></a></li>
            {% endfor %}
        </ul>
        
            
    {% endif %}
        
{% endblock content %}
    

templates/showcase/index.html
{% extends 'showcase/base.html' %}

{% block title %}
    Showcase
{% endblock title %}


{% block content %}
    
    {% if brand_list %}
        <h1 style='position:relative'>Производители</h1>
        {% for brand in brand_list %}
            <a href="{{ brand.get_absolute_url }}">{{ brand.brand_name }}</a><br>
        {% endfor %}
    {% else %}
        Пока нет производителей  
    {% endif %}
    
    {% if phone_list %}
        <h1>Телефоны</h1>
        {% for phone in phone_list  %}
        <a href="{{ phone.phone_brand.get_absolute_url }}">{{ phone.phone_brand }}</a> <a href="{{ phone.get_absolute_url }}">{{ phone.phone_model }}</a><br>
            <img src="{{ phone.phone_image.url }}" height="100"><br>
        {% endfor %}
        <a href="{% url 'phones' %}">Посмотреть все</a>
            
        
    {% endif %}
        
<button type="submit" id="but" style="position: relative;">Animate Me</button>

{% endblock content %}
    

templates/showcase/phone_create.html
{% extends 'showcase/base.html' %}

{% block title %}
    Create phone
{% endblock title %}
    

{% block content %}
    <form method="POST" enctype="multipart/form-data" action="{% url 'create_phone' %}">
        {% csrf_token %}
        
        {% for f in form %}
            {{ f }}<br>
        {% endfor %}
        <button type="submit">Добавить</button>
    </form>

{% endblock content %}
    

templates/showcase/phone_detail.html
{% extends 'showcase/base.html' %}

{% block title %}
    {{ phone.phone_model }}
{% endblock title %}

{% block content %}
    <h1><a href="{{phone.phone_brand.get_absolute_url }}">{{ phone.phone_brand }}</a> {{ phone.phone_model }}</h1><br>
    <img src="{{ phone.phone_image.url }}"><br>
    {{ phone.phone_specs }}
{% endblock content %}
    
    

templates/showcase/phone_list.html
{% extends 'showcase/base.html' %}

{% block title %}
    Phones
{% endblock title %}
    
{% block content %}
    {% if phones_list %}
        {% for phone in phones_list  %}
        <a href="{{ phone.phone_brand.get_absolute_url }}">{{ phone.phone_brand }}</a> <a href="{{ phone.get_absolute_url }}">{{ phone.phone_model }}</a><br>
        <img src="{{ phone.phone_image.url }}" height="100"><br>
        {% endfor %}
    {% else %}
     Телефонов пока нет
    {% endif %}  


{% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
{% endif %}
<span class="current">
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
</span>
{% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
{% endblock content %}
    

    

templates/showcase/search.html
{% if search_list %} 
    {% for el in search_list %}
        <a href="{{ el.get_absolute_url }}">{{ el }}</a>  
    {% endfor %}
{% else %}
    Нет результатов     
{% endif %}
    